### PR TITLE
Environment variables and added .env

### PR DESCRIPTION
**Pull request by jacobaraujo7**
Added .env file support.
Also added Stacktrace to better find errors.

### CODE REVIEW

**Comment by medz** [comment]
@Ali1Ammar @skillLan What do you think of this new feature?

**Comment by jacobaraujo7** [comment]
https://www.prisma.io/docs/guides/development-environment/environment-variables#using-env-files

**Comment by medz** [comment]
> https://www.prisma.io/docs/guides/development-environment/environment-variables#using-env-files

I don't think this is well supported by simply parsing `.env`. The current implementation of dotenv on pub.dev is fine. Maybe we need to create a dotenv ourselves (the reason is that I tried to contact the dotenv author and got no response.)

**Comment by medz** [comment]
@jacobaraujo7 I have rethought this problem, we may need to redesign the configuration, and solve the problem by the way:

1. Simpler and more direct format than dotenv
2. All configuration names in the program inherit from Prisma JS/TS client
3. Easier custom configuration file names and paths
4. Runtime configuration is easier to move and read
5. Runtime configuration allows sharing configuration from downstream

For this, I created a new requirement issue to document this feature 👉 #15

**Comment by jacobaraujo7** [comment]
Hello.
I'm taking into account how Prisma works in Node. Currently I don't know how it works in Go or Python.

My projects with Prisma use .env in key/value format, which I supported in this PR.

The objective of this feature is to bring the Dart prism closer and closer to the prism used in NodeJS, making it easier to understand that it already comes from this stack.

Personally, I prefer to add the environment variable directly to the system, but as many use it, I decided to make this effort.

**Comment by medz** [comment]
If Dart allows environment variables to be overwritten at runtime, it may be good to configure with .env. However, the environment variable of Dart VM is read-only and cannot be overwritten or appended. The experience of using dotenv in Dart is really bad.

**Comment by medz** [comment]
Maybe we can give the option downstream, use the dot priama runtime configuration, or dotenv, depending on how it is configured in pubspce.yaml and the .env file is loaded by default.

**Comment by jacobaraujo7** [comment]
@medz I agree with this point. It really is much better to add the environment variables directly into the system or with --define. 
My point is about the marketing of the tool, since some Prisma users already have the habit of using .env in their projects and this practice is referenced in the official Prisma documentation.
However, if we are going to disregard the .env, we will keep [this commit](https://github.com/odroe/prisma-dart/pull/13/commits/d8560f9b771541ebd5be2fb4f47faca27f9e31e8) preventing null errors and [this commit](https://github.com/odroe/prisma-dart/pull/13/commits/a60510d4fa6cf1322522015a711be29fb918816d). 

I see that this commit has already been added, so I believe it is ready. I will close this pullrequest.

**Comment by jacobaraujo7** [comment]
I made a new PR with only this 2 commits.
https://github.com/odroe/prisma-dart/pull/16

**Comment by medz** [comment]
@jacobaraujo7 Released version 2.1.0 👉 https://github.com/odroe/prisma-dart/releases/tag/2.1.0

Environment variable configuration using `.env` files is covered.

**Pull request closed without merging**
